# installation a partir de l'image de logstash

FROM debian:latest

RUN echo "Bienvenue dans l'outil de création de limage LAP" \
&& echo "powered by" \
&& echo "__/\\\________/\\\________/\\\\\\\\\_        " \
&& echo " _\/\\\_______\/\\\_____/\\\////////__       " \
&& echo "  _\/\\\_______\/\\\___/\\\/___________      " \
&& echo "   _\/\\\\\\\\\\\\\\\__/\\\_____________     " \
&& echo "    _\/\\\/////////\\\_\/\\\_____________    " \
&& echo "     _\/\\\_______\/\\\_\//\\\____________   " \
&& echo "      _\/\\\_______\/\\\__\///\\\__________  " \
&& echo "       _\/\\\_______\/\\\____\////\\\\\\\\\_ " \
&& echo "        _\///________\///________\/////////__" \
&& sleep 5

RUN apt-get update -yq \
&& apt-get install wget unzip cron -yq \
&& export DEBIAN_FRONTEND=noninteractive \
&& apt-get clean -y \
&& mkdir /var/log/cron && touch /var/log/cron/error.log

COPY cronJob /etc/cron.d/cronJob

RUN crontab /etc/cron.d/cronJob

CMD ["cron", "-f"]